on:
  pull_request:
    types:
    # A closed pull request makes the checks on the other
    # pull request on the same base outdated.
    - closed
    # Adding the autosquash label to a pull request can
    # trigger an update or a merge.
    - labeled
name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    if: contains(github.event.pull_request.labels.*.name, 'rebase')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
